image:
  repository: ghcr.io/cloudraftio/metrics-app
  tag: 1.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

secret:
  password: MYPASSWORD

serviceAccount:
  create: true

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80


ingress:
  enabled: false
