apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metrics-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /counter
        pathType: Prefix
        backend:
          service:
            name: {{ include "metrics-app.fullname" . }}
            port:
              number: {{ .Values.service.port }}

